= Interface became awesome in Java 8!!
Ted Roeloffzen
:hp-tags: java, interface, default method

== Interfaces FTW!
In een https://topicusonderwijs.github.io/2016/01/28/C-D-I-Vette-truukjes-met-Instance.html[vorig blog], en de daaraan gerelateerde blogs, is gesproken over CDI en alle toffe dingen die gaan kunnen worden met CDI.
Een van de mooie zaken die je met CDI mooi op kunt lossen is dat je gemakkelijk één of meerdere instanties van een bepaalde interface kunt laten injecteren. 
Dit bracht mij op het idee om eens goed te gaan kijken naar het type `interface`. + 

De interface is toch één van de belangrijkste bouwstenen van Java. Buitengewoon handig bij het schrijven van een API, maar tot Java 8 ook wel een beetje beperkt. Wanneer je een implementatie van een interface methode wilde kunnen hergebruiken in meerdere classes, dan zat je alweer vaak vast aan een (abstracte) class, maar die past niet altijd in je class hierarchy. Dan moet je code gaan dupliceren of nog wat anders proberen. Gelukkig heeft Java 8 twee nieuwe features voor de interface toegevoegd.

== Functional interfaces
Er is een nieuw type interface toegevoegd in Java 8, de zogenaamde Functional Interface. Dit is een interface met maar één abstract method. Dit is te doen door de annotatie `@FunctionalInterface` aan de interface toe te voegen. Dit is geen vereiste. Elke interface met maar één abstract method is in principe een functional interface, echter wanneer de annotatie eraan toegevoegd is, wordt door de compiler ook gecheckt of er maar één abstact method is. +

De reden dat dit type interface toegevoegd is, heeft te maken met een andere nieuwe toevoeging in Java 8, namelijk lambda's. Ook wel eens anonymous functions genoemd. Wat lambda's precies zijn en hoe je ze in kunt zetten, is wellicht iets voor een volgende blog.

== Static methods
Een andere toevoeging in Java 8 is de mogelijkheid om static methods toe te voegen aan interfaces. Voorheen was je genoodzaakt om static methods in de class zelf, in een (abstract) superclass of in een soort util-class toe te voegen. Dit had als nadeel dat je code die bij elkaar hoorde, niet altijd netjes bij elkaar kon plaatsen. Bijvoorbeeld bij enums die een interface implementeerde, aangezien inheritance bij enums niet is toegestaan. +

Voorheen hadden we bijvoorbeeld 2 enums die een vrijwel identieke implementatie van een aantal methodes hadden. +
`BPVStatus`
[source, java]
----
public static List<BPVStatus> getBronCommuniceerbareStatussen()
{
	List<BPVStatus> result = new ArrayList<BPVStatus>();
	for (BPVStatus status : values())
	{
		if (status.isDuoCommuniceerbaar())
		{
			result.add(status);
		}
    }
	return result;
}
----
`VerbintenisStatus`
[source, java]
----
public static List<VerbintenisStatus> getBronCommuniceerbareStatussen()
{
	List<VerbintenisStatus> result = new ArrayList<VerbintenisStatus>();
	for (VerbintenisStatus status : values())
	{
		if (status.isDuoCommuniceerbaar())
		{
			result.add(status);
		}
	}
	return result;
}
----

Zoals je ziet zijn deze methodes vrijwel identiek. Er zit heel veel boilerplate-code in en er is eigenlijk maar één verschil tussen deze methodes en dat is het type dat gebruikt wordt. +
Voorheen was het echter niet mogelijk om deze methode ergens te delen, tenzij je er een util-class voorschreef. 
Doordat deze twee enums toch al een interface deelden, leek het mij een goed plan om deze methode in de interface te plaatsen. Met een beetje refactorwerk ziet hij er uiteindelijk als volgt uit.

[source, java]
----
static <T extends Enum<T> & DuoCommuniceerbaar<T>> List<T> getStatussenObvPredicate(Class<T> enumClass)
{
	return Arrays.stream(enumClass.getEnumConstants())
    		.filter(DuoCommuniceerbaar::isDuoCommuniceerbaar)
			.collect(toList());
}
----
Doordat dit wel iets zou veranderen aan de aanroep van de methode, de juiste class moet namelijk meegegeven worden, heb ik de methodes wel in de enums laten zien, maar ziet de implementatie nu nog zo uit.

[source, java]
----
public static List<BPVStatus> getBronCommuniceerbareStatussen()
{
	return DuoCommuniceerbaar.getBronCommuniceerbareStatussen(BPVStatus.class);
}
----

Dit is natuurlijk maar één toepassing voor static methods en er zijn er vast meer. Maar ik denk dat dit wel de kracht aangeeft van static methods.

== Default methods 

Kijk en nu komen we echt in de mooie nieuwe functionaliteit van Java 8. Default methods openen namelijk een geheel nieuwe deur voor Java. Bij het refactoren van Java en het toevoegen van `Streams` en `Lambda's` is er gekeken hoe dit op een zo'n goed mogelijke manier gedaan kon worden. Doordat de ontwikkelaars elke collection binnen Java de mogelijkheid wilde geven om als `Stream` te gebruiken, wilde ze een abstract method stream() toevoegen aan de collection-interface. Echter de implementatie van die methode is in elke subclass hetzelfde. Dit is één van de oorzaken geweest dat men `default methods` heeft gecreëerd. +
Een methode, in een interface, kan als `default` gemarkeerd worden, door de methode een body te geven en het keyword `default` +
Zoals in `Collection.java`
[source, java]
----
default Stream<E> stream() {
	return StreamSupport.stream(spliterator(), false);
}
----
Doordat deze `default method` is toegevoegd krijgen alle classes die de Collection-interface implementeren gratis en voor niets de methode `stream()`. +

Een plek waar we dit bijvoorbeeld zelf gebruiken is bij `SerializablePredicate`. Doordat we ook Guava gebruiken hebben we zowel de Predicate van Java als van Guava. Doordat we in onze code maar één type willen gebruiken, die ook nog eens serializable is, is de interface `SerializablePredicate` in het leven geroepen. Dit is een interface die extend van de Guava-predicate, de Java-predicate en Serializable. Normaliter was het echter niet mogelijk om deze interface echter als `Functional interface` te gebruiken. Dit wordt veroorzaakt doordat de Java- en Guava-versie van Predicate niet dezelfde methode vereisen. Dit is als volgt opgelost met een `Default method`.

[source, java]
----
@Override
public default boolean apply(T t)
{
	return test(t);
}
----
Op deze manier krijg één van de twee methodes een body en blijft er maar één abstract method over. Hierdoor blijft ook deze interface een `Functional interface` en kan deze derhalve als `lambda` gebruikt worden. +

Met `default methods` wordt het nu bijvoorbeeld ook mogelijk om multiple inheritance te gebruiken. 

=== Multiple inheritance
Multiple inheritance wordt als volgt omschreven door https://en.wikipedia.org/wiki/Multiple_inheritance[wikipedia]:  *_Multiple inheritance_* _is a feature of some object-oriented computer programming languages in which an object or class can inherit characteristics and features from more than one parent object or parent class._ +

In Java 8 is dat deels mogelijk gemaakt d.m.v. interfaces met default methods. Ik zeg hier heel bewust deels, omdat het multiple inheritance m.b.t. state niet mogelijk is, omdat interface geen state hebben. 
[source, java]
----
public interface Logger
{
	default void log(String string)
   	{
   		System.out.println(string);
   	}
}

public interface Adder
{
	default int add(int i1, int i2)
   	{
   		return i1 + i2;
   	}
}

public class LoggingAdder implements Logger, Adder
{
	public static void main(String[] args)
	{
		LoggingAdder la = new LoggingAdder();
		la.log("Uitkomst van 4 + 5 = " + la.add(4, 5));
	}
}
----
=== Multiple inheritance problem

